version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
#     - "--providers.file.watch=true"
#      - "--providers.file.filename=simplified_certificates.yml"
#      - "--providers.file.filename=/etc/traefik/dynamic_conf/simplified_certificates.yml"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
      - "./traefik_dynamic_conf:/etc/traefik/dynamic_conf:ro"
    networks:
      - web

  frontend:
    image: frontend-image:latest
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
      - VITE_USE_HTTPS=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - web
    depends_on:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.docker.network=web"

networks:
  web:
    driver: bridge


# to run:
# docker-compose -f minimal-docker-compose.yml up -d

# to stop:
# docker-compose -f minimal-docker-compose.yml down