tls:
  certificates:
    - certFile: /certs/localhost.crt
      keyFile: /certs/localhost.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/localhost.crt
        keyFile: /certs/localhost.key
#  options:
#     default:
#       minVersion: VersionTLS12

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    http-catchall:
      rule: hostregexp(`{host:.+}`)
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal

    websecure-catchall:
      rule: hostregexp(`{host:.+}`)
      entrypoints:
        - websecure
      service: noop@internal
      tls: {}
      #   {{ if ne .Env.CERT_RESOLVER "" }}
      #   certResolver: {{ .Env.CERT_RESOLVER }}
       #  {{ end }}


   {{- $cert_resolver := env "CERT_RESOLVER" -}}
   {{- if ne $cert_resolver "" }}
   certificatesResolvers:
     le:
       acme:
         email: {{ env "LETSENCRYPT_EMAIL" }}
         storage: /letsencrypt/acme.json
         httpChallenge:
           entryPoint: web
   {{- end }}